### ISSUE TITLE
Accept and store webmentions preemptively for domains that aren't signed up yet

### ISSUE THREAD

**Issue by snarfed** [aaronpk/webmention.io#182] opened 2022-11-12 23:38 UTC
A somewhat exotic idea: when I post a response to a page on a site that doesn't yet support webmentions, I'd love to default to sending the webmention to webmention.io. It could start collecting them preemptively for any domain, even domains that aren't signed up yet. If/when a given domain starts accepting wms, it could use webmention.io and have a backlog of historical webmentions, or it could export them and import them into its own endpoint.

Odd idea, I know, just a thought.

**Comment by aaronpk** [comment] 2023-08-19 17:02
I'm going to close this as not planned. One of the changes I eventually want to make with this project is to be even more explicit about only accepting webmentions for sites that have actually signed up. There are already some weird edge cases caused by the current behavior which allows webmention.io to accept webmentions on an account for sites that are not explicitly added, and I want to get rid of that behavior. This feature would make it even worse, sorry!

**Closed by aaronpk** 2023-08-19 17:02 UTC
Labels: wontfix
